instance_name       = "db23cfree"
instance_shape      = "VM.Standard.E4.Flex"
ssh_public_key_path = "server.key.pub"
ssh_private_key_path = "server.key"
subnet_cidr         = "10.0.0.0/24"
vcn_cidr            = "10.0.0.0/16"
region              = "eu-frankfurt-1"